/**
 * The version must be declared ONCE, in package.json.
 *
 * It used to live in three places — package.json, a string literal in
 * src/index.ts, and server.json (twice) — coordinated only by a
 * `// Keep in sync with package.json` comment. It drifted anyway: server.json
 * sat at 2.8.1 while package.json was 2.9.0 and the MCP handshake advertised
 * 2.9.0, so the MCP Registry listed a release that was never published with
 * those contents.
 *
 * Now src/index.ts derives it at runtime (src/version.ts) and server.json is
 * regenerated by scripts/sync-version.mjs on `npm version`. These tests pin
 * both halves: that the derivation is real, and that the one remaining copy
 * actually matches.
 */
import { execFileSync } from "node:child_process";
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import { SERVER_VERSION } from "../src/version.js";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const read = (p: string) => readFileSync(join(root, p), "utf8");
const pkgVersion = JSON.parse(read("package.json")).version as string;

describe("version sync", () => {
  it("package.json carries a plain semver version", () => {
    expect(pkgVersion).toMatch(/^\d+\.\d+\.\d+$/);
  });

  it("the version advertised in the MCP handshake is read from package.json", () => {
    expect(SERVER_VERSION).toBe(pkgVersion);
  });

  it("index.ts does not hardcode a version literal", () => {
    // The regression that started all this. If someone re-inlines the literal,
    // SERVER_VERSION would still pass above while the real handshake diverges.
    const serverBlock = read("src/index.ts").match(/new Server\(\s*\{[\s\S]{0,400}?\}/)?.[0] ?? "";
    expect(serverBlock, "expected to find the new Server({...}) literal").toContain("name:");
    expect(serverBlock).not.toMatch(/version:\s*["'`]\d+\.\d+\.\d+/);
    expect(serverBlock).toContain("SERVER_VERSION");
  });

  it("every version in the registry manifest matches package.json", () => {
    const manifest = JSON.parse(read("server.json"));
    const versions = [manifest.version, ...manifest.packages.map((p: { version: string }) => p.version)];
    expect(versions.length).toBeGreaterThanOrEqual(2);
    for (const v of versions) expect(v).toBe(pkgVersion);
  });

  it("sync-version is idempotent — a no-op when already in sync", () => {
    const before = read("server.json");
    const out = execFileSync("node", [join(root, "scripts/sync-version.mjs")], {
      cwd: root,
      encoding: "utf8",
    });
    expect(out.trim()).toBe("");
    expect(read("server.json")).toBe(before);
  });
});
